[project]
name = 'BeLoyal'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.BusinessRegistry]
path = 'contracts/BusinessRegistry.clar'
clarity_version = 2
epoch = 2.5

[contracts.LoyaltyCore]
path = 'contracts/LoyaltyCore.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
